'use client';
import { FormEvent, useState } from 'react';
const PHONE='919620581931';
const IMG='https://www.godrejproperties.com/landing-page/bangalore/residential/godrej-florenne/Images/';
const homes=[['4 BED OPTIMA','4 BHK'],['4 BHK PREMIA','4 BHK'],['4 BED LUXE','4 BHK'],['5 BHK LUXE','5 BHK']] as const;
export default function Home(){
 const [selected,setSelected]=useState('4 BHK'); const [sent,setSent]=useState(false);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=['Godrej Florenne enquiry','Name: '+f.get('name'),'Mobile: '+f.get('phone'),'Email: '+f.get('email'),'Configuration: '+f.get('configuration')].join('\n');window.open('https://wa.me/'+PHONE+'?text='+encodeURIComponent(msg),'_blank');setSent(true)};
 return <main>
 <header className="site-nav">
 <a className="logo" href="#top" aria-label="Godrej Florenne home">
  <span className="logo-mark" aria-hidden="true"><i/><b/></span>
  <span className="logo-word">GODREJ</span><strong>FLORENNE</strong><small>OFF SOUKYA ROAD · WHITEFIELD, BENGALURU</small>
 </a>
 <nav aria-label="Primary navigation">
  <a href="#story">OVERVIEW</a><a href="#highlights">HIGHLIGHTS</a><a href="#amenities">AMENITIES</a><a href="#location">LOCATION</a><a href="#gallery">GALLERY</a><a href="#enquiry">CONTACT US</a>
 </nav>
 <div className="header-right"><span className="gp-mark">G</span><span>GODREJ<br/><b>PROPERTIES</b></span></div>
 <a className="nav-cta" href="#enquiry">ENQUIRE NOW</a>
</header>
 <section id="top" className="hero-new"><div className="hero-image"/><div className="hero-shade"/><div className="hero-copy-new"><p className="kicker">NEW LAUNCH · OFF WHITEFIELD-HOSKOTE ROAD</p><h1>A touch of France.<br/><i>A whole lot of home.</i></h1><p className="hero-sub">Premium 4 & 5 BHK row houses in Whitefield, Bengaluru, created for a life with more space, privacy and character.</p><div className="hero-actions-new"><a className="gold-btn" href="#enquiry">Request Details</a><a className="line-btn" href="#residences">Explore Residences</a></div></div><div className="hero-card"><span>GODREJ FLORENNE</span><strong>4 & 5 BHK</strong><small>Premium Row Houses</small><div className="hero-card-line"/><b>₹5.40 Cr.*</b><small>Starting from</small></div><div className="hero-scroll">SCROLL TO DISCOVER ↓</div></section>
 <section id="story" className="editorial"><div className="editorial-label">C'EST MAGNIFIQUE</div><div className="editorial-copy"><h2>Every frame tells a story of grandeur.</h2><p>Inspired by French Renaissance architecture and traditional châteaux, Godrej Florenne brings a distinctive character to Whitefield.</p><p>Light, courtyards and outdoor spaces come together to create a private world that feels elegant, warm and distinctly yours.</p><a href="#enquiry" className="text-arrow">Discover Florenne ↗</a></div><div className="editorial-image"><img src={IMG+'courtyard.webp'} alt="Godrej Florenne courtyard"/><span>La Grande Cour</span></div></section>
 <section id="highlights" className="manifesto"><div className="manifesto-image"><img src={IMG+'3rd_section.webp'} alt="Godrej Florenne outdoor living"/></div><div className="manifesto-copy"><p className="kicker dark">UN SOUFFLE DE NATURE</p><h2>Every day deserves a little more outdoors.</h2><p>The outdoors becomes an extension of home — for morning walks, children's play, evenings with friends and quiet pauses beneath the sky.</p><div className="manifesto-points"><div><b>La Terrasse</b><span>Where every gathering feels like home.</span></div><div><b>La Pergola</b><span>A green horizon just outside your door.</span></div><div><b>La Grande Cour</b><span>Your world, beautifully centred.</span></div></div></div></section>

 <section id="gallery" className="florenne-slider" aria-label="Godrej Florenne project gallery"><div className="slider-heading"><p className="kicker dark">A GLIMPSE OF FLORENNE</p><h2>Scenes from<br/><i>beautiful living.</i></h2></div><div className="slider-track"><div className="slide"><img src={IMG+'2nd_section.webp'} alt="Godrej Florenne French-inspired row houses"/><span>01 · The Residences</span></div><div className="slide"><img src={IMG+'courtyard.webp'} alt="Godrej Florenne courtyard"/><span>02 · La Grande Cour</span></div><div className="slide"><img src={IMG+'3rd_section.webp'} alt="Godrej Florenne outdoor landscape"/><span>03 · Outdoor Living</span></div><div className="slide"><img src={IMG+'pergola.webp'} alt="Godrej Florenne landscaped pergola"/><span>04 · The Landscape</span></div></div><div className="slider-dots" aria-hidden="true"><i/><i/><i/><i/></div></section>
 <section className="numbers"><div><span>01</span><b>4 & 5 BHK</b><small>Signature row-house residences</small></div><div><span>02</span><b>Whitefield</b><small>Off Whitefield-Hoskote Road</small></div><div><span>03</span><b>₹5.40 Cr.*</b><small>Starting from</small></div><div><span>04</span><b>Sep 2031</b><small>Possession</small></div></section>
 <section id="residences" className="residences"><div className="section-heading"><p className="kicker dark">BONJOUR, BEAUTIFUL LIFE.</p><h2>Homes with room<br/>for your story.</h2><p>Explore the four signature residence types and request the detailed floor plan for the home that interests you.</p></div><div className="residence-list">{homes.map(([name,type],i)=><button key={name} className={'residence-row '+(selected===type?'active':'')} onClick={()=>setSelected(type)}><span className="residence-number">0{i+1}</span><span className="residence-main"><b>{name}</b><small>{type}</small></span><span className="residence-note">Detailed plan available on request.</span><span className="residence-arrow">↗</span></button>)}</div><div className="plan-visual"><div className="plan-art"><i/><i/><i/><i/><i/><i/><i/></div><div><span>SELECTED CONFIGURATION</span><b>{selected}</b><p>Detailed floor plans and current availability are shared on request.</p><a href="#enquiry">Get Floor Plan →</a></div></div></section>
 <section id="amenities" className="amenity-section"><div className="amenity-intro"><p className="kicker">A LITTLE MORE JOIE DE VIVRE</p><h2>More ways to unwind.<br/>More reasons to get together.</h2></div><div className="amenity-image"><img src={IMG+'pergola.webp'} alt="Godrej Florenne landscaped pergola"/></div><div className="amenity-grid">{[['01','Kids Play Area','Spaces for pure childhood joy.'],['02','Landscape Padel','A place for a quick game with family or friends.'],['03','View Amphitheatre','An open-air setting for performances and celebrations.'],['04','Gazebo','A quiet covered corner to pause outdoors.']].map(([n,t,c])=><article key={t}><span>{n}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section id="location" className="location-new"><div className="location-copy"><p className="kicker dark">LA BELLE ADRESSE</p><h2>Close to everything.<br/>Away from the ordinary.</h2><p>Godrej Row Houses, Whitefield — off Whitefield-Hoskote Road, Hemmandahalli. A well-connected East Bengaluru address.</p><a className="text-arrow dark-arrow" href="https://www.google.com/maps/search/?api=1&query=XRC2%2BQJP%2C%20Hemmandahalli%2C%20Karnataka%20560117" target="_blank" rel="noreferrer">Open in Maps ↗</a></div><div className="location-map"><img src={IMG+'map_new_desk.webp'} alt="Godrej Florenne location map"/></div><div className="connectivity">{[['08','Soukya Road'],['15','Whitefield Railway Station'],['20','Hope Farm Junction'],['20','Kadugodi Metro Station'],['25','ITPL / Whitefield Main Road'],['40','KR Puram']].map(([time,place])=><div key={place}><b>{time}<sup> min</sup></b><span>{place}</span></div>)}</div></section>
 <section className="closing"><img src={IMG+'2nd_section.webp'} alt="Godrej Florenne architecture"/><div className="closing-overlay"/><div className="closing-copy"><p className="kicker">A HOME WITH A POINT OF VIEW</p><h2>Come home to<br/><i>something magnificent.</i></h2><a className="gold-btn" href="#enquiry">Arrange a Conversation</a></div></section>
 <section id="enquiry" className="enquiry-new"><div className="enquiry-copy"><p className="kicker dark">YOUR NEXT CHAPTER STARTS HERE</p><h2>Let's find<br/>your Florenne.</h2><p>Request the latest floor plans, pricing and project details. Our representative will connect with you directly.</p><a href={'tel:+'+PHONE} className="enquiry-phone">+91 96205 81931</a></div><form className="luxury-form" onSubmit={submit}><label>FULL NAME<input name="name" required placeholder="Your name"/></label><label>MOBILE NUMBER<input name="phone" required inputMode="tel" placeholder="Your mobile number"/></label><label>EMAIL ADDRESS<input name="email" type="email" required placeholder="Your email address"/></label><label>CONFIGURATION<select name="configuration" value={selected} onChange={e=>setSelected(e.target.value)}><option>4 BHK</option><option>5 BHK</option><option>Not decided</option></select></label><button className="gold-btn submit-btn" type="submit">Request Details →</button>{sent&&<p className="form-success">WhatsApp opened with your enquiry details.</p>}<small>By submitting, you agree to be contacted regarding this project.</small></form></section>
 <footer className="footer-new"><div className="footer-brand"><span>GODREJ</span><b>FLORENNE</b><small>WHITEFIELD · BENGALURU</small></div><div className="footer-contact"><a href={'tel:+'+PHONE}>+91 96205 81931</a><a href={'https://wa.me/'+PHONE} target="_blank" rel="noreferrer">WhatsApp</a></div><div className="footer-disclaimer">Independent enquiry/marketing website. Project information is presented for enquiry purposes based on referenced Godrej Florenne material. Prices, plans, specifications and availability are subject to change. GST, stamp duty, registration and applicable charges are additional. RERA: PRM/KA/RERA/1250/304/PR/150926/008942 and PRM/KA/RERA/1250/304/PR/150926/008943.</div></footer>
 <div className="floating-new"><a href={'https://wa.me/'+PHONE} target="_blank" rel="noreferrer">WhatsApp</a><a href={'tel:+'+PHONE}>Call</a></div>
 </main>
}