'use client';
import { FormEvent, useEffect, useState } from 'react';

const PHONE='919620581931', DISPLAY_PHONE='+91 96205 81931';
const IMG='https://www.godrejproperties.com/landing-page/bangalore/residential/godrej-florenne/Images/';
const plans=[['4 BED OPTIMA','4 BHK'],['4 BHK PREMIA','4 BHK'],['4 BED LUXE','4 BHK'],['5 BHK LUXE','5 BHK']] as const;
const gallery=[['2nd_section.webp','Chateau-inspired row houses'],['3rd_section.webp','Landscaped outdoor spaces'],['pergola.webp','Refined outdoor living'],['courtyard.webp','Private courtyard character']] as const;

export default function Home(){
 const [selected,setSelected]=useState('Not decided');
 const [lightbox,setLightbox]=useState<string|null>(null);
 const [sent,setSent]=useState(false);
 const [slide,setSlide]=useState(0);
 useEffect(()=>{const id=window.setInterval(()=>setSlide(s=>(s+1)%gallery.length),4500);return()=>window.clearInterval(id)},[]);
 const choose=(type:string)=>{setSelected(type);document.getElementById('enquiry')?.scrollIntoView({behavior:'smooth'})};
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const msg=['Godrej Florenne enquiry','Name: '+f.get('name'),'Mobile: '+f.get('phone'),'Email: '+f.get('email'),'Configuration: '+f.get('configuration')].join('\n');window.open('https://wa.me/'+PHONE+'?text='+encodeURIComponent(msg),'_blank','noopener,noreferrer');setSent(true)};
 return <main>
  <header className="nav"><a className="brand" href="#top">GODREJ FLORENNE</a><nav><a href="#experience">Experience</a><a href="#gallery">Gallery</a><a href="#amenities">Amenities</a><a href="#location">Location</a><a href="#plans">Plans</a></nav><a className="nav-call" href={'tel:+'+PHONE}>Call {DISPLAY_PHONE}</a></header>
  <section id="top" className="hero"><div className="hero-overlay"/><div className="hero-content"><p className="eyebrow">GODREJ ROW HOUSES · WHITEFIELD</p><h1>C'est magnifique.<br/><em>A whole lot of home.</em></h1><p className="hero-copy">Premium 4 & 5 BHK row houses at Off Whitefield-Hoskote Road, Hemmandahalli.</p><div className="hero-actions"><a className="btn primary" href="#enquiry">Schedule a Site Visit</a><a className="btn ghost" href={'tel:+'+PHONE}>Call {DISPLAY_PHONE}</a></div><div className="hero-stats"><span><b>4 & 5 BHK</b><small>Row Houses</small></span><span><b>₹5.40 Cr*</b><small>From</small></span><span><b>Sep 2031</b><small>Possession</small></span></div></div></section>
  <section id="experience" className="section intro"><div><p className="eyebrow">C'EST MAGNIFIQUE</p><h2>Every frame tells a story of grandeur.</h2></div><div className="copy"><p>From the chateau-inspired facade to the refined interiors within, Godrej Florenne brings a French-inspired character to everyday living.</p><p>Homes are designed with open courtyards, sunlit interiors and private outdoor spaces at every level.</p></div></section>
  <section id="gallery" className="gallery-section"><div className="gallery-head"><div><p className="eyebrow">THE FLORENNE EXPERIENCE</p><h2>Designed to be remembered.</h2></div><p>More project visuals, automatically sliding every few seconds. Swipe on mobile or use the arrows.</p></div><div className="slider"><div className="slide-track" style={{transform:'translateX(-'+slide*100+'%)'}}>{gallery.map(([file,label])=><figure key={file} className="slide" onClick={()=>setLightbox(IMG+file)}><img src={IMG+file} alt={label}/><figcaption>{label}<span>Tap to enlarge</span></figcaption></figure>)}</div><button className="slide-arrow prev" aria-label="Previous image" onClick={()=>setSlide(s=>(s-1+gallery.length)%gallery.length)}>‹</button><button className="slide-arrow next" aria-label="Next image" onClick={()=>setSlide(s=>(s+1)%gallery.length)}>›</button><div className="slide-dots">{gallery.map(([,label],i)=><button key={label} className={i===slide?'active':''} aria-label={'Show image '+(i+1)} onClick={()=>setSlide(i)}/>)}</div></div></section>
  <section id="amenities" className="section"><p className="eyebrow">A LITTLE MORE JOIE DE VIVRE</p><h2>More ways to unwind.<br/>More reasons to get together.</h2><div className="cards">{['Kids Play Area','Landscape Padel','Landscape View Amphitheatre','Gazebo'].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>Thoughtfully crafted outdoor spaces for everyday enjoyment.</p></article>)}</div></section>
  <section className="quote-band"><p>“Un souffle de nature, Every Day”</p><span>The outdoors gives you plenty of ways to make the most of everyday.</span></section>
  <section id="location" className="section location"><div><p className="eyebrow">LA BELLE ADRESSE</p><h2>In the heart of it all.</h2><p className="copy-text">Godrej Row Houses, Whitefield — Prime Address, Off Whitefield-Hoskote Road, Hemmandahalli.</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=XRC2%2BQJP%2C%20Hemmandahalli%2C%20Karnataka%20560117" target="_blank" rel="noreferrer">Get Direction →</a></div><div className="map-wrap"><img src={IMG+'map_new_desk.webp'} alt="Godrej Florenne location map"/></div></section>
  <section className="section connectivity"><p className="eyebrow">LOCATION ADVANTAGE</p><h2>Connected to what matters.</h2><div className="nearby">{[['8 min','Soukya Road'],['15 min','Whitefield Railway Station'],['20 min','Hope Farm Junction / Whitefield-Hoskote Road'],['20 min','Kadugodi Metro Station (Purple Line)'],['25 min','ITPL / Whitefield Main Road'],['40 min','KR Puram']].map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</div></section>
  <section id="plans" className="section plans"><div><p className="eyebrow">BONJOUR, BEAUTIFUL LIFE.</p><h2>Choose your signature residence.</h2><p className="copy-text">Select a residence type and request the detailed plan from our site representative.</p><p className="selected-plan">Selected: <b>{selected}</b></p></div><div className="plan-list">{plans.map(([name,type])=><button key={name} className={'plan-item '+(selected===type?'active':'')} onClick={()=>choose(type)}><span><b>{name}</b><small>{type}</small></span><strong>Request plan →</strong></button>)}</div></section>
  <section id="enquiry" className="enquiry"><div><p className="eyebrow">YOUR LIFE OF INDULGENCE BEGINS HERE</p><h2>Schedule a site visit.</h2><p>Share only the essential details. Your enquiry opens directly in WhatsApp.</p><a href={'tel:+'+PHONE} className="phone">{DISPLAY_PHONE}</a><a href={'https://wa.me/'+PHONE} target="_blank" rel="noreferrer" className="whatsapp-link">WhatsApp us →</a></div><form onSubmit={submit}><label>Name<input name="name" required placeholder="Full name"/></label><label>Mobile<input name="phone" required inputMode="tel" placeholder="Mobile number"/></label><label>Email<input name="email" type="email" required placeholder="Email address"/></label><label>Configuration<select name="configuration" value={selected} onChange={e=>setSelected(e.target.value)}><option>Not decided</option><option>4 BHK</option><option>5 BHK</option></select></label><button className="btn primary" type="submit">Send Enquiry on WhatsApp</button>{sent&&<p className="success">WhatsApp opened with your enquiry details.</p>}</form></section>
  {lightbox&&<div className="lightbox" role="dialog" aria-modal="true" onClick={()=>setLightbox(null)}><button className="lightbox-close" onClick={()=>setLightbox(null)}>×</button><img src={lightbox} alt="Godrej Florenne visual enlarged" onClick={e=>e.stopPropagation()}/></div>}
  <footer><div><b>GODREJ FLORENNE</b><span>Off Whitefield-Hoskote Road, Hemmandahalli, Whitefield, Bengaluru</span></div><div><a href={'tel:+'+PHONE}>{DISPLAY_PHONE}</a><a href={'https://wa.me/'+PHONE} target="_blank" rel="noreferrer">WhatsApp</a></div><small>Independent enquiry/marketing website. Project information is presented for enquiry purposes based on referenced Godrej Florenne material. Prices, plans, specifications and other project details are subject to change. GST, stamp duty, registration and applicable charges are additional. RERA: PRM/KA/RERA/1250/304/PR/150926/008942 and PRM/KA/RERA/1250/304/PR/150926/008943.</small></footer>
  <div className="floating-actions"><a className="float-whatsapp" href={'https://wa.me/'+PHONE+'?text='+encodeURIComponent('Hello, I am interested in Godrej Florenne. Please share details.')} target="_blank" rel="noreferrer">WhatsApp</a><a className="float-call" href={'tel:+'+PHONE}>Call</a></div>
 </main>
}